export default {
  title: 'potatoTheme',
  editorTheme: 'vs-dark',

  // general, login page, general messages (like toast msg)
  colorsOne: {
    primary: '#33ff6f',
    secondary: '#9b05b0',
    tertiary: '#abc',
    successBg: '#107d59de',
    successText: '#eee',
    warningBg: '#8e673ede',
    warningText: '#eee',
    errorBg: '#5b3f35de',
    errorText: '#eee',
    infoBg: '#663e8ede',
    infoText: '#eee',
    textOne: '#ccc',
    textTwo: '#ccc',
    textThree: '#ccc',
    linkOne: '#eee',
    linkTwo: '#eee',
    linkThree: '#eee',
    titleOne: '#fff',
    titleTwo: '#fff',
    titleThree: '#fff',
    bgOne: '#222',
    bgTwo: '#333',
    bgThree: '#444',
    borderOne: '#333',
    borderTwo: '#444',
    borderThree: '#555',
    scrollbarTrack: '#303030cc',
    scrollbarThumb: '#161616cc',
  },

  // notes tree
  colorsTwo: {
    primary: '#33ff6f',
    secondary: '#9b05b0',
    tertiary: '#abc',
    successBg: '#107d59de',
    successText: '#eee',
    warningBg: '#8e673ede',
    warningText: '#eee',
    errorBg: '#5b3f35de',
    errorText: '#eee',
    infoBg: '#663e8ede',
    infoText: '#eee',
    textOne: '#6c6c6c',
    textTwo: '#888',
    textThree: '#aaa',
    linkOne: '#ececec',
    linkTwo: '#ddd',
    linkThree: '#ccc',
    titleOne: '#6c6c6c',
    titleTwo: '#888',
    titleThree: '#aaa',
    bgOne: '#222',
    bgTwo: '#222',
    bgThree: '#222',
    borderOne: '#393939',
    borderTwo: '#444',
    borderThree: '#555',
    scrollbarTrack: '#303030cc',
    scrollbarThumb: '#161616cc',
  },

  // note data
  colorsThree: {
    primary: '#33ff6f',
    secondary: '#9b05b0',
    tertiary: '#abc',
    successBg: '#107d59de',
    successText: '#eee',
    warningBg: '#8e673ede',
    warningText: '#eee',
    errorBg: '#5b3f35de',
    errorText: '#eee',
    infoBg: '#663e8ede',
    infoText: '#eee',
    textOne: '#6c6c6c',
    textTwo: '#ececec',
    textThree: '#aaa',
    linkOne: '#ececec',
    linkTwo: '#ddd',
    linkThree: '#ccc',
    titleOne: '#d9d9d9',
    titleTwo: '#888',
    titleThree: '#aaa',
    bgOne: '#282828',
    bgTwo: '#282828',
    bgThree: '#282828',
    borderOne: '#393939',
    borderTwo: '#444',
    borderThree: '#555',
    scrollbarTrack: '#303030cc',
    scrollbarThumb: '#161616cc',
  },

  // user menu
  colorsFour: {
    primary: '#33ff6f',
    secondary: '#9b05b0',
    tertiary: '#abc',
    successBg: '#107d59de',
    successText: '#eee',
    warningBg: '#8e673ede',
    warningText: '#eee',
    errorBg: '#5b3f35de',
    errorText: '#eee',
    infoBg: '#663e8ede',
    infoText: '#eee',
    textOne: '#6c6c6c',
    textTwo: '#888',
    textThree: '#aaa',
    linkOne: '#ececec',
    linkTwo: '#ddd',
    linkThree: '#ccc',
    titleOne: '#6c6c6c',
    titleTwo: '#888',
    titleThree: '#aaa',
    bgOne: '#222',
    bgTwo: '#333',
    bgThree: '#444',
    borderOne: '#393939',
    borderTwo: '#444',
    borderThree: '#555',
    scrollbarTrack: '#303030cc',
    scrollbarThumb: '#161616cc',
  },

  // note editor
  colorsFive: {
    primary: '#33ff6f',
    secondary: '#9b05b0',
    tertiary: '#abc',
    successBg: '#107d59de',
    successText: '#eee',
    warningBg: '#8e673ede',
    warningText: '#eee',
    errorBg: '#5b3f35de',
    errorText: '#eee',
    infoBg: '#663e8ede',
    infoText: '#eee',
    textOne: '#ccc',
    textTwo: '#ccc',
    textThree: '#ccc',
    linkOne: '#eee',
    linkTwo: '#eee',
    linkThree: '#eee',
    titleOne: '#fff',
    titleTwo: '#fff',
    titleThree: '#fff',
    bgOne: '#222',
    bgTwo: '#333',
    bgThree: '#444',
    borderOne: '#333',
    borderTwo: '#444',
    borderThree: '#555',
    scrollbarTrack: '#303030cc',
    scrollbarThumb: '#161616cc',
  },

  // top bar, console and note bar
  colorsSix: {
    primary: '#33ff6f',
    secondary: '#9b05b0',
    tertiary: '#abc',
    successBg: '#107d59de',
    successText: '#eee',
    warningBg: '#8e673ede',
    warningText: '#eee',
    errorBg: '#5b3f35de',
    errorText: '#eee',
    infoBg: '#663e8ede',
    infoText: '#eee',
    textOne: '#ccc',
    textTwo: '#5e5e5e',
    textThree: '#ccc',
    linkOne: '#eee',
    linkTwo: '#eee',
    linkThree: '#eee',
    titleOne: '#fff',
    titleTwo: '#fff',
    titleThree: '#fff',
    bgOne: '#282828',
    bgTwo: '#333',
    bgThree: '#202020',
    borderOne: '#333',
    borderTwo: '#444',
    borderThree: '#555',
    scrollbarTrack: '#303030cc',
    scrollbarThumb: '#181818cc',
  },
};
