#!/bin/bash

echo "HANDLE CHALLENGES"

read -r -d '' top_readme_content << EOM
<br />

[◄ Back link](https://github.com/imtherouser/Studies/study-codes/Exercism/#🖖)

<br />

**The readme content below was generated by Exercism itself.**

<br />

---------------------------
EOM

folders=($(ls typescript))

for folder in "${folders[@]}"; do
  link="* [$folder](https://github.com/imtherouser/Studies/study-codes/Exercism/typescript/$folder#🖖)"

  if !(grep -Fxq "$link" "readme.md"); then
    echo "$link" >> "readme.md"

    echo "$top_readme_content

$(cat typescript/$folder/README.md)" > "typescript/$folder/README.md"

    echo "*
!README.md
!*.ts
" > "typescript/$folder/.gitignore"

    echo -e "➤ Challenge added: $folder"
  fi
done

echo "👍 Done."